### ISSUE TITLE
incorrect spelling of "background_color"

### ISSUE THREAD

**Issue by flooder1704** [rinqu-eu/love2d-console#4]
https://github.com/rinqu-eu/love2d-console/blob/a755a38b811c2bf8e4b1cb468aafc705439753c1/console/console.lua#L21
Should be `background_color = {0.16, 0.16, 0.16, 0.50}`

Missing a "u" in backgro**u**nd

**Comment by rinqu-eu** [comment]
Fixed in c410d27a61608e311e3651cc788eb6f60edf80ec
Thanks
