### ISSUE TITLE
Error when entering command in console

### ISSUE THREAD

**Issue by Jcalderwood1** [rinqu-eu/love2d-console#5]
`Error

console/console.lua:507: 'for' limit must be a number

Traceback

console/console.lua:507: in function 'AddToOutput'
console/console.lua:572: in function <console/console.lua:562>
console/console.lua:812: in function <console/console.lua:808>
[C]: in function 'xpcall'`

**Comment by rinqu-eu** [comment]
Can you tell me what were you doing when you got the error?
What command were you using?

Does 113b0786a48f9e824fb242e76f9f6eee8287217d fix the problem in case?

**Comment by rinqu-eu** [comment]
Does 113b0786a48f9e824fb242e76f9f6eee8287217d fix the problem in your case?

**Comment by Jcalderwood1** [comment]
Hey! Thanks for the quick response. 

I received the error anytime I entered anything into the console, valid or invalid.

113b078 fixed the issue in that I no longer get an error when I enter something into the console. However, now when I enter something nothing happens. No output.

**Comment by rinqu-eu** [comment]
It's weird that you are getting this error in a 1st place.

What LOVE version are you using?

**Comment by Jcalderwood1** [comment]
Version 11.3 (Mysterious Mysteries)

**Comment by rinqu-eu** [comment]
That is so weird. Could you paste in the function causing troubles from YOUR file?

**Comment by Jcalderwood1** [comment]
Okay so this was an issue with my code. I had a function defined with a name of select(). Something under the hood must call a function called select() when your console receives input. If I comment out or rename my select() function, the console works as expected! 

Sorry for the confusion. I am newish to Lua and am still getting a grip on the strange details.

**Comment by rinqu-eu** [comment]
That's good to know! No problem.
The code does indeed use "select" which is a Lua buildin function. You should probably rename yours ;)
Have fun coding!

**Comment by rinqu-eu** [comment]
That's good to know! No problem.
The code does indeed use "select" which is a Lua buildin function. You should probably rename yours ;)
Have fun coding!

**Comment by Jcalderwood1** [comment]
Thanks! Really cool project, btw. I am excited to make full use of it.
